create table Trainer_Info(Trainer_Id varchar(20)  PRIMARY KEY, Salutaion varchar(7), Trainer_Name varchar(30), Trainer_Location varchar(30), Trainer_Track varchar(15), Trainer_Qualification varchar(100), Trainer_experience varchar(11), Trainer_Email varchar(100), Trainer_Password varchar(20));
create table Batch_Info(Batch_Id varchar(20)  PRIMARY KEY, Batch_Owner varchar(30), Batch_BU_Name varchar(30));
create table Module_Info(Module_Id varchar(20)  PRIMARY KEY, Module_Name varchar(40), Module_Duration int(11));
create table Associate_Info(Associate_Id varchar(20) PRIMARY KEY, Salutation varchar(7), Associate_Name varchar(30), Associate_Location varchar(30), Associate_Track varchar(15), Associate_Qualification varchar(200), Associate_Email varchar(100), Associate_Password varchar(20));
create table Questions(Questions_Id varchar(20)  PRIMARY KEY, Module_Id varchar(20), Questions_Text varchar(900), FOREIGN KEY(Module_Id) REFERENCES Module_Info(Module_Id));
create table Associate_Status(Associate_Id varchar(20), Module_Id varchar(20), Start_Date varchar(20), End_Date varchar(20), AFeedbackGiven varchar(20), TFeedbackGiven varchar(20),FOREIGN KEY(Module_Id) REFERENCES Module_Info(Module_Id), FOREIGN KEY(Associate_Id) REFERENCES Associate_Info(Associate_Id) );
create table Trainer_Feedback(Trainer_Id varchar(20), Question_Id varchar(20), Batch_Id varchar(20), Module_Id varchar(20), Trainer_Rating int(11), FOREIGN KEY(Module_Id) REFERENCES Module_Info(Module_Id), FOREIGN KEY(Batch_Id) REFERENCES Batch_Info(Batch_Id), FOREIGN KEY(Trainer_Id) REFERENCES Trainer_Info(Trainer_Id), FOREIGN KEY(Question_Id) REFERENCES Questions(Question_Id) );
create table Associate_Feedback(Associate_Id varchar(20), Question_Id varchar(20), Module_Id varchar(20), Associate_Rating int(11), FOREIGN KEY(Module_Id) REFERENCES Module_Info(Module_Id), FOREIGN KEY(Associate_Id) REFERENCES Associate_Info(Associate_Id), FOREIGN KEY(Question_Id) REFERENCES Questions(Question_Id) );
create table Login_Tables(User_Id varchar(20), User_Password varchar(20));
insert into Trainer_Info(Trainer_Id,Salutaion,Trainer_Name,Trainer_Location,Trainer_Track,Trainer_Qualification,Trainer_experience,Trainer_Email,Trainer_Password) values('F001','Mr.','PANKAJ GHOSH','Pune','Java,Bachelor of Technology','12','Pankaj.Ghosh@alliance.com','fac1@123');
insert into Trainer_Info(Trainer_Id,Salutaion,Trainer_Name,Trainer_Location,Trainer_Track,Trainer_Qualification,Trainer_experience,Trainer_Email,Trainer_Password) values ('F002','Mr.','SANJAY RADHAKRISHNAN ','Bangalore','DotNet','Bachelor of Technology','12','Sanjay.Radhakrishnan@alliance.com','fac2@123');
insert into Trainer_Info(Trainer_Id,Salutaion,Trainer_Name,Trainer_Location,Trainer_Track,Trainer_Qualification,Trainer_experience,Trainer_Email,Trainer_Password) values ('F003','Mr','VIJAY MATHUR','Chennai','Mainframe','Bachelor of Technology','10','Vijay.Mathur@alliance.com','fac3@123');
insert into Trainer_Info(Trainer_Id,Salutaion,Trainer_Name,Trainer_Location,Trainer_Track,Trainer_Qualification,Trainer_experience,Trainer_Email,Trainer_Password) values ('F004','Mrs.','NANDINI NAIR','Kolkata','Java','Master of Computer Applications','9','Nandini.Nair@alliance.com','fac4@123');
insert into Batch_Info(Batch_Id,Batch_Owner,Batch_BU_Name) values ('B001','MRS.SWATI ROY','MSP');
insert into Batch_Info(Batch_Id,Batch_Owner,Batch_BU_Name) values ('B002','MRS.ARURNA K','HEALTHCARE');

